services:
  - type: web
    name: notice-pdf-generator
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./start.sh"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
